### ISSUE TITLE
Erreur dans le code Ansible

### ISSUE THREAD

**Issue by alex-faivre** [blbcrv/ProjetDevops#1]
Pour l'erreur Ansible rencontrée dans la sortie d'erreur, il vous manque une directive source dans votre code d'appel de construction de l'image.

Il aurait fallu utiliser : 

`source: build `

```
    - name: Construire l'image Docker
      community.docker.docker_image:
        path: /home/ubuntu/webapp/
        name: webapp
        source: build
        tag: latest
        state: present
```

Avec ça vous auriez pu avoir le dépannage de votre pb et aller plus loin. La prochaine fois demandez moi par mail.

Alex
